title: Kuhlcloud - IT Networks and more
tagline: A blog about IT Networks and more
author:
  name: Daniel Kuhl
  email: blog@kuhlcloud.de
description: >- # this means to ignore newlines until "baseurl:"
  Currently it is focused on IT Network Automation & Programmability 
  including further evolving in this area, obtaining certifications, 
  and knowledge sharing. Enjoy reading!
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.kuhlcloud.de # the base hostname & protocol for your site, e.g. http://example.com
social:
  name: Daniel Kuhl
  links:
    - https://twitter.com/daniel1820815
    - https://techhub.social/@daniel1820815
    - https://www.linkedin.com/in/daniel-kuhl-b8b9603b
    - https://github.com/daniel1820815
twitter:
  username: daniel1820815
  card: summary
mastodon:
  - username: daniel1820815
    instance: techhub.social
issues_repo: daniel1820815/daniel1820815.github.io

header_pages:
  - about.md
  - categories.html
  - privacy.md

minima:
  skin: dark
  social_links:
    twitter: daniel1820815
    github: daniel1820815
    linkedin: daniel-kuhl-b8b9603b

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
